# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('delay', models.IntegerField(default=0)),
                ('created', models.CharField(max_length=20)),
                ('karma', models.IntegerField(default=0)),
                ('about', models.CharField(max_length=20)),
                ('submitted', models.CharField(max_length=200)),
            ],
        ),
    ]
