# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('type', models.CharField(max_length=10)),
                ('by', models.CharField(max_length=10)),
                ('time', models.DateTimeField(verbose_name='date publised')),
                ('text', models.CharField(max_length=200)),
                ('dead', models.BooleanField(default=False)),
                ('parent', models.IntegerField(default=0)),
                ('kids', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('score', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=100)),
                ('parts', models.CharField(max_length=200)),
                ('descendant', models.IntegerField(default=0)),
            ],
        ),
    ]
