# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20170422_0640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='item',
            name='time',
            field=models.IntegerField(verbose_name='date publised'),
        ),
    ]
